routes/admin.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//后台管理路由
Route::middleware(['admin.login','admin.auth','admin.demo'])->group(function(){

    //Index控制器
    Route::controller(\App\Http\Controllers\Admin\IndexController::class)->group(function (){
        Route::get('/', 'index')->name('admin.index');
        Route::get('/home', 'home')->name('admin.home');
        Route::get('/download', 'download')->name('admin.download');
        Route::get('/skin', 'skin')->name('admin.skin');
        Route::get('/nav-style', 'navStyle')->name('admin.nav-style');
    });

    //Public控制器
    Route::controller(\App\Http\Controllers\Admin\PublicController::class)->group(function (){
        Route::any('/login','login')->name('admin.login');
        Route::get('/logout','logout')->name('admin.logout');
        Route::get('/noauth','noauth')->name('admin.noauth');
    });

    //Common控制器
    Route::controller(\App\Http\Controllers\Admin\CommonController::class)->group(function (){
        Route::post('/uploadimg','uploadimg')->name('admin.uploadimg');
        Route::post('/uploadvideo','uploadvideo')->name('admin.uploadvideo');
        Route::post('/uploadfile','uploadfile')->name('admin.uploadfile');
        Route::get('/cropper','cropper')->name('admin.cropper');
        Route::any('/lockscreen','lockscreen')->name('admin.lockscreen');
        Route::any('/cacheclear','cacheclear')->name('admin.cacheclear');
        Route::any('/repass','repass')->name('admin.repass');
    });


    //系统模块
    Route::prefix('system')->name('system.')->group(function (){
        //配置管理
        Route::controller(\App\Http\Controllers\Admin\System\ConfigController::class)->prefix('config')->name('config.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::any('/add', 'add')->name('add');
            Route::any('/edit', 'edit')->name('edit');
            Route::post('/drop', 'drop')->name('drop');
            Route::any('/site', 'site')->name('site');
            Route::post('/dropall', 'dropall')->name('dropall');
        });
        //组织部门
        Route::controller(\App\Http\Controllers\Admin\System\StructController::class)->prefix('struct')->name('struct.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::any('/add', 'add')->name('add');
            Route::any('/edit', 'edit')->name('edit');
            Route::post('/drop', 'drop')->name('drop');
            Route::any('/tree', 'tree')->name('tree');
        });
        //岗位管理
        Route::controller(\App\Http\Controllers\Admin\System\PositionController::class)->prefix('position')->name('position.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::any('/add', 'add')->name('add');
            Route::any('/edit', 'edit')->name('edit');
            Route::post('/drop', 'drop')->name('drop');
            Route::post('/dropall', 'dropall')->name('dropall');
        });
        //菜单管理
        Route::controller(\App\Http\Controllers\Admin\System\MenuController::class)->prefix('menu')->name('menu.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::any('/add', 'add')->name('add');
            Route::any('/edit', 'edit')->name('edit');
            Route::post('/drop', 'drop')->name('drop');
            Route::any('/tree', 'tree')->name('tree');
        });
        //角色管理
        Route::controller(\App\Http\Controllers\Admin\System\RoleController::class)->prefix('role')->name('role.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::any('/add', 'add')->name('add');
            Route::any('/edit', 'edit')->name('edit');
            Route::post('/drop', 'drop')->name('drop');
            Route::post('/dropall', 'dropall')->name('dropall');
            Route::post('/setstatus', 'setstatus')->name('setstatus');
            Route::any('/auth', 'auth')->name('auth');
            Route::any('/datascope', 'datascope')->name('datascope');
        });
        //人员管理
        Route::controller(\App\Http\Controllers\Admin\System\AdminController::class)->prefix('admin')->name('admin.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::any('/add', 'add')->name('add');
            Route::any('/edit', 'edit')->name('edit');
            Route::post('/drop', 'drop')->name('drop');
            Route::post('/dropall', 'dropall')->name('dropall');
            Route::any('/tree', 'tree')->name('tree');
            Route::post('/ajaxtreelist', 'ajaxtreelist')->name('ajaxtreelist');
        });
        //登录日志
        Route::controller(\App\Http\Controllers\Admin\System\LoginlogController::class)->prefix('loginlog')->name('loginlog.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::post('/dropall', 'dropall')->name('dropall');
        });
        //通知公告
        Route::controller(\App\Http\Controllers\Admin\System\NoticeController::class)->prefix('notice')->name('notice.')->group(function (){
            Route::any('/index', 'index')->name('index');
            Route::any('/add', 'add')->name('add');
            Route::any('/edit', 'edit')->name('edit');
            Route::post('/drop', 'drop')->name('drop');
            Route::post('/dropall', 'dropall')->name('dropall');
        });

    });

    //工具模块
    Route::prefix('tool')->group(function (){
        Route::controller(\App\Http\Controllers\Admin\Tool\FormController::class)->prefix('form')->group(function (){
            Route::get('/build', 'build');
        });
        Route::controller(\App\Http\Controllers\Admin\Tool\GenController::class)->prefix('gen')->group(function (){
            Route::any('/create', 'create');
        });
        Route::controller(\App\Http\Controllers\Admin\Tool\UploadController::class)->prefix('upload')->group(function (){
            Route::any('/index', 'index');
            Route::any('/add', 'add');
            Route::any('/edit', 'edit');
            Route::post('/drop', 'drop');
            Route::post('/dropall', 'dropall');
        });
    });
});

routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/error', function (Request $request) {
    $msg = $request->get('msg','发生错误了');
    $code = $request->get('code','400');
    return view('error',['code'=>$code,'msg'=>$msg]);
})->name('error');

Route::get('/success', function (Request $request) {
    $msg = $request->get('msg','操作成功');
    $code = $request->get('code','200');
    return view('success',['code'=>$code,'msg'=>$msg]);
})->name('success');

Route::get("/", function () {
    return redirect(route("admin.index"));
});

app/Http/Controllers/Admin/System/AdminController.php
<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF V2.0 [快捷通用基础管理开发平台]
// +----------------------------------------------------------------------
// | Author: 冰舞 <357145480@qq.com>
// +----------------------------------------------------------------------
declare (strict_types=1);

namespace App\Http\Controllers\Admin\System;

use App\Extends\Cache\PositionCache;
use App\Extends\Helpers\Functions;
use App\Extends\Helpers\Result;
use App\Extends\Libs\AdminCommonAction;
use App\Extends\Services\System\AdminPosService;
use App\Extends\Services\System\AdminRoleService;
use App\Extends\Services\System\AdminStructService;
use App\Extends\Services\System\StructService;
use App\Extends\Validates\System\AdminValidate;
use App\Models\System\Admin;
use App\Models\System\Role;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;

class AdminController extends System
{
    use AdminCommonAction;

    protected string $model = Admin::class;
    protected string $validate = AdminValidate::class;

    /**
     * 选择人员视图
     * @return View
     */
    public function tree(): View
    {
        $mult = $this->request->get('mult',0);
        $ids = $this->request->get('ids', '');
        return $this->render('',['user_ids'=>$ids,'mult'=>$mult]);
    }

    /**
     * 人员视图获取人员列表
     * @return View|JsonResponse
     */
    public function ajaxtreelist(): View|JsonResponse
    {
        if(!$this->request->isMethod('POST')){
            return $this->toError('请求类型错误');
        }
        $params = [];
        $post = $this->request->post();

        $userIdList = $this->listStructParse($post);
        if($userIdList === false){
            $params['where']['id'] = '0';
        }elseif($userIdList){
            $params['in']['id'] = array_unique($userIdList);
        }
        $params['like']['realname'] = $post['like']['realname']??'';
        $params['where']['status'] = '1';

        $params['field'] = ['id','realname','status','create_time'];
        $query = DB::table($this->model::tableName());
        $query = $this->indexWhere($query, $params);
        $root_id = config('b5net.root_admin_id');
        $query = $query->where('id','<>',$root_id);
        $pageSize = intval($post['pageSize'] ?? 10);
        $pageNum = intval($post['pageNum'] ?? 1);
        $pageNum = $pageNum < 1 ? 1 : $pageNum;
        $pageStart = ($pageNum-1)*$pageSize;
        $count = $query->count();
        $query = $query->offset($pageStart)->limit($pageSize);
        $list = $query->get();
        $list = $this->indexAfter($list?Functions::stdToArray($list):[]);
        return Result::success('操作成功',$list, ['total' => $count]);
    }

    /**
     * 首页渲染
     * @return View
     */
    protected function indexRender(): View
    {
        $root_id = config('b5net.root_admin_id');
        $roleList = Role::bSelect();
        return $this->render('', ['root_id' => $root_id,'roleList'=>$roleList]);
    }

    /**
     * 首页列表查询前条件处理
     * @param array $params
     * @return array
     */
    protected function indexBefore(array $params): array
    {
        $userIdList = [];
        //角色处理
        $role_id = $params['role_id'] ?? '';
        if($role_id){
            $roleList = (new AdminRoleService())->getAdminIdByRoleId($role_id);
            if(!$roleList){
                $params['where']['id'] = '0';
                return $params;
            }
            $userIdList = $roleList;
        }

        //组织架构处理
        $structUserList = $this->listStructParse($params);
        if($structUserList === false){
            $params['where']['id'] = '0';
        }elseif($structUserList){
            $userIdList = array_merge($userIdList,$structUserList);
        }

        if($userIdList){
            $params['in']['id'] = array_unique($userIdList);
        }
        return $params;
    }

    /**
     * 列表查询时，组织架构处理
     * @param array $post
     * @return array|false
     */
    protected function listStructParse(array $post): bool|array
    {
        $userIdList = [];
        //组织架构处理
        $contains = $post['contains']??0;
        $root_struct_id = config('b5net.root_struct_id');
        $struct_id = $post['structId'] ?? '';
        if ($struct_id) {
            $structList = [];
            if($contains){
                if($root_struct_id != $struct_id){
                    //获取所有子组织
                    $structList = (new StructService())->getChildList($struct_id,true);
                    $structList[] = $struct_id;
                }
            }else{
                $structList[] = $struct_id;
            }
            if($structList){
                //获取组织下的用户
                $list = (new AdminStructService())->getAdminIdByStructId($structList);
                $userIdList = $list?:false;
            }
        }
        return $userIdList;
    }

    /**
     * 首页列表处理
     * @param array $list
     * @return array
     */
    protected function indexAfter(array $list): array
    {
        $structService = new AdminStructService();
        $roleService = new AdminRoleService();
        $posService = new AdminPosService();
        foreach ($list as $key => $value) {
            $structInfo = $structService->getStructByAdminId($value['id'], true);
            $struct_name = '';
            if($structInfo){
                $struct_name = $structInfo['name'];
                if($structInfo['parent_name']){
                    $parent_name = explode(',',$structInfo['parent_name']);
                    $parent_name = array_pop($parent_name);
                    $struct_name = $parent_name.'/'.$struct_name;
                }
            }
            $value['struct_name'] = $struct_name;

            $roleList = $roleService->getRoleByAdmin($value['id'], true);
            $roleList = $roleList ? array_column($roleList, 'name') : [];
            $value['role_name'] = implode(',', $roleList);

            $posInfo = $posService->getPosByAdmin($value['id'],true);
            $value['pos_name'] = $posInfo?$posInfo['name']:'';
            $value['pos_key'] = $posInfo?$posInfo['poskey']:'';

            $list[$key] = $value;
        }
        return $list;
    }

    /**
     * 添加页渲染
     * @return View
     */
    protected function addRender(): View
    {
        $roleList = Role::bSelect([], ['listsort' => 'asc']);
        $posList = PositionCache::lists();
        return $this->render('', ['roleList' => $roleList,'posList'=>$posList]);
    }

    /**
     * 编辑页渲染
     * @param array $info
     * @return View
     */
    protected function editRender(array $info): View
    {
        $structInfo = (new AdminStructService())->getStructByAdminId($info['id'], true);
        $roleId = (new AdminRoleService())->getRoleByAdmin($info['id']);
        $roleList = Role::bSelect([], ['listsort' => 'asc']);
        $posList = PositionCache::lists();
        $posId = (new AdminPosService())->getPosByAdmin($info['id']);
        return $this->render('', ['info'=>$info,'roleList' => $roleList,'structInfo'=>$structInfo,'roleId'=>$roleId,'posList'=>$posList,'posId'=>$posId]);
    }

    /**
     * 验证前进行数据处理
     * @param array $data
     * @param string $type
     * @return array
     */
    protected function validateBefore(array $data, string $type): array
    {
        if (isset($data['password']) && !$data['password']) {
            if ($type == 'add') {
                $data['password'] = '123456';
            } else if ($type == 'edit') {
                unset($data['password']);
            }
            if(isset($data['realname']) && !$data['realname']){
                $data['realname'] = $data['username'];
            }
        }
        return $data;
    }

    /**
     * 添加和编辑保存前对数据进行处理
     * @param array $data
     * @param string $type
     * @return array|string
     */
    protected function saveBefore(array $data, string $type): array|string
    {
        if($type == 'add' || $type == 'edit'){
            if(isset($data['password'])){
                if(!$data['password']) return '登录密码不能为空';
                $data['password'] = md5($data['password']);
            }
        }
        return $data;
    }

    /**
     * 添加和编辑后更新角色和组织信息
     * @param array $data
     * @param string $type
     */
    protected function saveAfter(array $data, string $type): void
    {
        if ($type == 'add' || $type == 'edit') {
            $roles = $this->request->post('roles', '');
            $struct = $this->request->post('struct', '');
            $pos = $this->request->post('pos', '');

            (new AdminRoleService())->update($data['id'], $roles);
            (new AdminStructService())->update($data['id'], $struct);
            (new AdminPosService())->update($data['id'], $pos);
        }
    }

    /**
     * 删除前判断
     * @param array $data
     * @return bool|string
     */
    protected function deleteBefore(array $data)
    {
        $root_id = config('b5net.root_admin_id');
        if ($data['id'] == $root_id) {
            return '默认超级管理员无法删除';
        }
        return true;
    }

    /**
     * 删除后操作
     * @param array $data
     */
    protected function deleteAfter(array $data): void
    {
        //删除管理员角色
        (new AdminRoleService())->deleteByAdmin($data['id']);

        //删除管理员组织部门
        (new AdminStructService())->deleteByAdmin($data['id']);

        //删除管理员岗位
        (new AdminPosService())->deleteByAdmin($data['id']);
    }
}

app/Http/Controllers/Admin/System/LoginlogController.php
<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF V2.0 [快捷通用基础管理开发平台]
// +----------------------------------------------------------------------
// | Author: 冰舞 <357145480@qq.com>
// +----------------------------------------------------------------------
declare (strict_types = 1);

namespace App\Http\Controllers\Admin\System;

use App\Extends\Libs\AdminCommonAction;
use App\Models\System\Loginlog;

class LoginlogController extends System
{
    use AdminCommonAction;
    protected string $model = Loginlog::class;


}

resources/views/admin/system/struct/add.blade.php
@extends('admin.layout.form')

@section('content')
<form class="form-horizontal m" id="form-add">
    <input type="hidden" name="parent_id" id="treeId" value="{{$root_id}}">

    <div class="form-group">
        <label class="col-sm-3 control-label is-required">上级组织：</label>
        <div class="col-sm-8">
            <div class="input-group">
                <input type="text" id="treeName" value="{{$root_name}}" class="form-control" placeholder="请选择上级组织" readonly autocomplete="off"/>
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">组织名称：</label>
        <div class="col-sm-8">
            <input type="text" name="name" value="" class="form-control" placeholder="请输入组织名称" required autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">显示顺序：</label>
        <div class="col-sm-8">
            <input type="number" name="listsort" value="0" class="form-control" placeholder="请输入显示顺序" required autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">负责人：</label>
        <div class="col-sm-8">
            <input type="text" name="leader" value="" class="form-control" placeholder="请输入负责人" autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">联系电话：</label>
        <div class="col-sm-8">
            <input type="text" name="phone" value="" class="form-control" placeholder="请输入联系电话" autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">状态：</label>
        <div class="col-sm-8">
            <label class="radio-box">
                <input type="radio" name="status" value="0"/> 有效
            </label>
            <label class="radio-box">
                <input type="radio" name="status" value="1" checked/> 无效
            </label>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label ">备注：</label>
        <div class="col-sm-8">
            <textarea name="note" class="form-control" placeholder="请输入备注"></textarea>
        </div>
    </div>
</form>
@stop

@section('script')
    <script>
        $(function () {
            //选择组织树
            $("#treeName").click(function () {
                var treeId = $("#treeId").val();
                var url=urlcreate("{{route('system.struct.tree')}}","id=" + treeId);
                var options = {
                    title: '组织选择',
                    width: "380",
                    url: url,
                    callBack: doSubmit
                };
                $.modal.openOptions(options);
            });
        });
        function doSubmit(index, layero){
            var body = layer.getChildFrame('body', index);
            $("#treeId").val(body.find('#treeId').val());
            $("#treeName").val(body.find('#treeName').val());
            layer.close(index);
        }
        function submitHandler() {
            if ($.validate.form()) {
                $.operate.save(oasUrl, $('#form-add').serialize());
            }
        }
    </script>
@stop

resources/views/admin/system/struct/edit.blade.php
@extends('admin.layout.form')

@section('content')
<form class="form-horizontal m" id="form-edit">
    <input type="hidden" name="id" value="{{$info['id']}}">
    <input type="hidden" name="parent_id" id="treeId" value="{{$info['parent_id']}}">

    <div class="form-group">
        <label class="col-sm-3 control-label is-required">上级组织：</label>
        <div class="col-sm-8">
            <div class="input-group">
                <input type="text" id="treeName" value="{{$info['parent_name']}}" class="form-control" placeholder="请选择上级组织" readonly autocomplete="off" @if($info['id'] == $root_id) disabled @endif/>
                <span class="input-group-addon"><i class="fa fa-search"></i></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">组织名称：</label>
        <div class="col-sm-8">
            <input type="text" name="name" value="{{$info['name']}}" class="form-control" placeholder="请输入组织名称" required autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">显示顺序：</label>
        <div class="col-sm-8">
            <input type="number" name="listsort" value="{{$info['listsort']}}" class="form-control" placeholder="请输入显示顺序" required autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">负责人：</label>
        <div class="col-sm-8">
            <input type="text" name="leader" value="{{$info['leader']}}" class="form-control" placeholder="请输入负责人" autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label">联系电话：</label>
        <div class="col-sm-8">
            <input type="text" name="phone" value="{{$info['phone']}}" class="form-control" placeholder="请输入联系电话" autocomplete="off"/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label is-required">状态：</label>
        <div class="col-sm-8">
            <label class="radio-box">
                <input type="radio" name="status" value="0" @if($info['status'] == '0') checked @endif/> 有效
            </label>
            <label class="radio-box">
                <input type="radio" name="status" value="1" @if($info['status'] == '1') checked @endif/> 无效
            </label>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-3 control-label ">备注：</label>
        <div class="col-sm-8">
            <textarea name="note" class="form-control" placeholder="请输入备注">{{$info['note']}}</textarea>
        </div>
    </div>
</form>
@stop

@section('script')
    <script>
        $(function () {
            //选择组织树
            $("#treeName").click(function () {
                var treeId = $("#treeId").val();
                var url=urlcreate("{{route('system.struct.tree')}}","id=" + treeId);
                var options = {
                    title: '组织选择',
                    width: "380",
                    url: url,
                    callBack: doSubmit
                };
                $.modal.openOptions(options);
            });
        });
        function doSubmit(index, layero){
            var body = layer.getChildFrame('body', index);
            $("#treeId").val(body.find('#treeId').val());
            $("#treeName").val(body.find('#treeName').val());
            layer.close(index);
        }
        function submitHandler() {
            if ($.validate.form()) {
                $.operate.save(oesUrl, $('#form-edit').serialize());
            }
        }
    </script>
@stop

resources/views/admin/system/struct/index.blade.php
@extends('admin.layout.layout')

@include('widget.asset.treetable')

@section('content')
    <div class="col-sm-12 search-collapse">
        <form id="role-form">
            <div class="select-list">
                <ul>
                    <li>
                        组织名称：<input type="text" name="like[name]" value="">
                    </li>
                    <li>组织状态：
                        <select name="where[status]">
                            <option value="">全部</option>
                            <option value="1">有效</option>
                            <option value="0">无效</option>
                        </select>
                    <li>
                    <li>
                        <a class="btn btn-primary btn-rounded btn-sm" onclick="$.treeTable.search()"><i class="fa fa-search"></i> 搜索</a>
                        <a class="btn btn-warning btn-rounded btn-sm" onclick="$.form.reset()"><i class="fa fa-refresh"></i> 重置</a>
                    </li>
                </ul>
            </div>
        </form>
    </div>
    <div class="btn-group-sm" id="toolbar" role="group">
        <a class="btn btn-success" onclick="$.operate.add(this)"><i class="fa fa-plus"></i> 新增</a>
        <a class="btn btn-info" id="expendinfobtn"><i class="fa fa-exchange"></i> 展开/折叠</a>
    </div>
    <div class="col-sm-12 select-table table-striped">
        <table id="bootstrap-tree-table"></table>
    </div>
@stop

@section('script')
    <script>
        var datas = '';
        $(function() {
            var options = {
                modalName: "组织部门",
                expandAll:true,
                columns: [{
                    field: 'selectItem',
                    radio: true
                },
                    {
                        title: '组织名称',
                        field: 'name',
                        formatter: function(value, row, index) {
                            if ($.common.isEmpty(row.icon)) {
                                return row.name;
                            } else {
                                return '<i class="' + row.icon + '"></i> <span class="nav-label">' + row.name + '</span>';
                            }
                        }
                    },
                    {
                        field: 'listsort',
                        title: '排序'
                    },
                    {
                        field: 'status',
                        title: '状态',
                        formatter: function(value, row, index) {
                            return $.view.statusShow(row,false);

                        }
                    },
                    {field: 'create_time', title: '创建时间', sortable: true},
                    {field: 'update_time', title: '更新时间',sortable: true,visible: false},
                    {field: 'note', title: '备注',visible: false},
                    {
                        title: '操作',
                        width: '20',
                        widthUnit: '%',
                        align: "left",
                        formatter: function(value, row, index) {
                            var actions = [];
                            actions.push('<a class="btn btn-success btn-xs" href="javascript:;" onclick="$.operate.edit(\'' + row.id + '\')"><i class="fa fa-edit"></i>编辑</a> ');
                            if(row.id != {{$root_id}}){
                                actions.push('<a class="btn btn-danger btn-xs" href="javascript:;" onclick="$.operate.remove(\'' + row.id + '\')"><i class="fa fa-remove"></i>删除</a> ');
                            }
                            return actions.join('');
                        }
                    }]
            };
            $.treeTable.init(options);
        });
    </script>
@stop

resources/views/admin/system/struct/tree.blade.php
@extends('admin.layout.form')

@include('widget.asset.ztree')

@section('content')
<style>
    body {height: auto;font-family: "Microsoft YaHei";background-color: #fff !important;}
    button {font-family: "SimSun", "Helvetica Neue", Helvetica, Arial;}
</style>
<input type="hidden" name='treeId' id='treeId' value='{{$struct_id}}'>
<input type="hidden" name='treeName' id='treeName' value=''>
<div class="wrapper">
    <div class="treeShowHideButton" onclick="$.tree.toggleSearch();">
        <label id="btnShow" title="显示搜索" style="display:none;">︾</label>
        <label id="btnHide" title="隐藏搜索">︽</label>
    </div>
    <div class="treeSearchInput" id="search">
        <label for="keyword">关键字：</label><input type="text" class="empty" id="keyword" maxlength="50">
        <button class="btn" id="btn" onclick="$.tree.searchNode()"> 搜索</button>
    </div>
    <div class="treeExpandCollapse">
        <a href="javascript:;" onclick="$.tree.expand()">展开</a> /
        <a href="javascript:;" onclick="$.tree.collapse()">折叠</a>
    </div>
    <div id="tree" class="ztree treeselect"></div>
</div>
@stop

@section('script')
    <script>
        $(function () {
            var options = {
                url: aUrl,
                @if($parent == '1')
                    showParentLevel:0,
                @else
                    showParentLevel:false,
                @endif
                expandLevel: 2
            };
            $.tree.init(options);
        });
    </script>
@stop